---
controller_credentials:
  - name: Mist API - Lab
    description: Juniper Mist API credentials for lab environment
    organization: Default
    credential_type: Juniper Mist API
    inputs:
      mist_token: "{{ lookup('ansible.builtin.env', 'MIST_TOKEN') }}"
      mist_base_url: "{{ lookup('ansible.builtin.env', 'MIST_BASE_URL') | default('https://api.mist.com', true) }}"
      org_id: "{{ lookup('ansible.builtin.env', 'ORG_ID') }}"
